GLOBAL:
  era: Run2_2017
  period: '2017'
  
WJetsToLNu_HT-2500ToInf:
  miniAOD: /WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM
  sampleType: mc
  
# TTToSemiLeptonic:
#  miniAOD: /TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM
#   sampleType: mc
# GluGluToHHTo2B2VLNu2J_node_cHHH1:
#   miniAOD: /GluGluToHHTo2B2VLNu2J_node_cHHH1_TuneCP5_PSWeights_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM
#   sampleType: mc